services:
  keycloak:
    image: jboss/keycloak:16.1.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8180:8080"
    volumes:
      - ./realms:/tmp/realms
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_IMPORT: /tmp/realms/humlib-realm.json
    deploy:
      resources:
        limits:
          memory: "${DOCKER_MEM_LIMIT_KEYCLOAK}"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    hostname: mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
