openapi: 3.0.1
info:
  title: HumLib - The Human Library in Computer Science
  description: 'This is the API specification for HumLib - the Human Library in Computer Science. This project aims to bring together children interested in the plethora of topics in IT and computer science experts.'
  termsOfService: http://example.org
  contact:
    email: admin@humlib
  license:
    name: MIT
    url: https://opensource.org/licenses/mit-license.php
  version: 0.0.1
externalDocs:
  description: Find out more about HumLib
  url: http://example.org
servers:
  - url: http://localhost:8080/
tags:
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about HumLib
      url: http://example.org
paths:
  /user:
    post:
      tags:
        - user
      summary: Create user
      security:
        - humlib_auth:
            - users_write
            # - write:users
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        default:
          description: successful operation
          content: { }
      x-codegen-request-body-name: body
  /user/{id}:
    get:
      tags:
        - user
      summary: Get user by user id
      security:
        - humlib_auth:
            - users_read
            # - read:users
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: 'The user id that needs to be fetched.'
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid user id supplied
          content: { }
        404:
          description: User not found
          content: { }
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
  securitySchemes:
    humlib_auth:
      type: openIdConnect
      openIdConnectUrl: http://localhost:8180/auth/realms/humlib/.well-known/openid-configuration
#    humlib_oauth2:
#      type: oauth2
#      flows:
#        authorizationCode:
#          authorizationUrl: http://localhost:8180/auth/realms/humlib/protocol/openid-connect/auth
#          tokenUrl: http://localhost:8180/auth/realms/humlib/protocol/openid-connect/token
#          scopes:
#            write:users: Modify user details
#            read:users: Get user details
