name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v2
      - name: "Install Java 17 Temurin"
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: "Execute gradle"
        run: ./gradlew build --no-daemon
      - name: "Upload test results"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "Unit test results"
          path: |
            build/test-results/**/*.xml
      - name: "Upload coverage report"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "jacocoTestReport"
          path: build/reports/jacoco/test/jacocoTestReport.xml

  event_file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
      - name: "Upload"
        uses: actions/upload-artifact@v2
        with:
          name: "event_file"
          path: ${{ github.event_path }}
