name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - run: ./gradlew build --no-daemon
      - name: "Upload Test Results"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: "Unit Test Results"
          path: |
            build/test-results/**/*.xml
      - name: "JaCoCo Report"
        uses: PavanMudigonda/jacoco-reporter@v2.3
        with:
          coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Comment coverage to PR"
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
  event_file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
      - name: "Upload"
        uses: actions/upload-artifact@v2
        with:
          name: "event_file"
          path: ${{ github.event_path }}
